name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t shivaraj .

  run_image:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run docker image
      run: docker run shivaraj