name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build -t webapp .
    
    - name: Run the Docker image
      run: |
        docker run -d -p 3000:3000 --name webapp-container webapp
        sleep 15 # Allow time for the container to start

    - name: Test the Docker image with curl
      run: |
        curl http://localhost:3000
