name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker build -t webapp .
        docker run -d webapp

  run_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run the Docker image
      run: | 
        docker run -d webapp

  test_curl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: curling
      run: | 
        curl http://localhost:3000 
  
